config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  devise_for :users

  resources :users, only: [:show, :edit, :update] #ユーザー情報

  #お題登録完了ページ
  get 'votes/complete' => 'votes#complete', as: 'complete'

  resources :votes, only: [:new, :create, :index, :show, :destroy, :update] do#投票お題
    resources :topics, only: [:create, :destroy] do #投票題
      resource :polls, only: [:create, :destroy] #投票
    end
  end

  resources :results, only: [:index, :show] #お題結果





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :vote, inverse_of: :topics
  has_many :polls, dependent: :destroy

  validates :body, presence: true

# 投票機能
  def polled_by?(user)
    polls.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  has_many :votes, dependent: :destroy
  has_many :polls, dependent: :destroy
  #has_many :favorites, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  has_many :topics, dependent: :destroy, inverse_of: :vote
  accepts_nested_attributes_for :topics
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def create
    vote = Vote.find(params[:vote_id])
    poll = current_user.polls.new(topic_id: params[:poll][:topic_id])
    poll.save
    redirect_to vote_path(vote)
  end

  def destroy
    vote = Vote.find(params[:vote_id])
    topic = Topic.find(params[:topic_id])
    poll = current_user.polls.find_by(topic_id: topic.id)
    poll.destroy
    redirect_to vote_path(vote)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @votes = Vote.all
  end

  def show
    vote = Vote.find(params[:id])
    @topics = vote.topics
    @vote = Vote.find(params[:id])

    @top_topics = []
    @topics.each do |topic|
      if @top_topics[0]
        if @top_topics[0].polls.count < topic.polls.count
         @top_topics = [topic]
        elsif @top_topics[0].polls.count == topic.polls.count
         @top_topics.push(topic)
        end
      else
        @top_topics.push(topic)
      end
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @votes = @user.votes
  end

  def edit
  end

  def update
  end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    @vote = Vote.new
    4.times { @vote.topics.build }
  end

  def complete
  end

  def create
    @vote = Vote.create(vote_params)
    @user = current_user

    # @vote.user_id = current_user.id
    if @vote.save
      redirect_to complete_path, notice: "You have created vote successfully."
    else
      render 'new'
    end
  end

  def index
    @votes = Vote.all
    #@topics = Topic.all
  end

  def show
    @poll = Poll.new
    @vote = Vote.find(params[:id])
    @topics = @vote.topics
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    redirect_to user_path(current_user)
  end

 def update
   @vote = Vote.find(params[:id])
   @vote.status = false
   @vote.update(vote_status_params)
   redirect_to user_path(current_user)
 end



  private

  def vote_params
    params.require(:vote).permit(:title, :body, topics_attributes:[:body]).merge(user_id: current_user.id)
  end

  def vote_status_params
    params.permit(:status)
  end

  # 直打ち防止
  def correct_user
    vote = Vote.find(params[:id])
    user = vote.user
    redirect_to votes_path if current_user != user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/homes/top.html.erb
<div class="center">
<h2>Welcome to YourVote</h2>
</div>
<div class="center">
<br><p>今悩んでいることを他人に投票で決めてもらおう！</p><br>
<p>優柔不断なので困ったときにその他大衆の意見を気軽に聞きたい！ という方に</p>
</div>

app/views/layouts/_error.html.erb
<% if resource.errors.any? %>
  <h3><%= resource.errors.count %>件のエラーが発生しました。</h3>
  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar under-line">
    <div class="navbar-header col-sm-2">
      <h1><%= link_to "YourVote", root_path, class: "navbar-left logo" %></h1>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "マイページ", user_path(current_user), class:'nav-logo margin-top-xs margin-right-xs' %></li>
          <li><%= link_to "VOTE一覧", votes_path, class:'nav-logo margin-top-xs margin-right-xs' %></li>
          <li><%= link_to "VOTE結果一覧", results_path, class:'nav-logo margin-top-xs margin-right-xs' %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'nav-logo margin-top-xs margin-right-xs' %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path, class:'nav-logo btn margin-top-xs margin-right-xs' %></li>
          <li><%= link_to "ログイン", new_user_session_path, class:'nav-logo btn margin-top-xs margin-right-xs' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourVote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://d3js.org/d3.v5.min.js"></script> <!--d3.jsの記述-->
  </head>
  <body>
    <div class="container body-line">
      <div class="row">
        <div class="header-line">
          <%= render "layouts/header" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
        <footer></footer>
    </div>
  </body>
</html>

app/views/results/index.html.erb
<h2>お題結果一覧</h2>
<table class="table">
  <thead>
    <tr>
			<th>タイトル</th>
			<th>本文</th>
		</tr>
	</thead>
  <tbody>
    <% @votes.each do |vote| %>
      <% if vote.status == true %>
      <% elsif vote.status == false %>
        <tr>
          <td><%= link_to vote.title, result_path(vote), class:"rounded black" %></td>
          <td><%= vote.body %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/results/show.html.erb
<h2>お題結果詳細データ</h2>
<div class="center">
<div class="col-xs-8">
  <div id="poll_chart"></div> <!--円グラフ-->
</div>
<div class="col-xs-4">
  <table class="table table-bordered">
    <thead>
		<tr>
			<th class="gothic"><b>お題</b></th>
			<th class="gothic"><b>票数</b></th>
		</tr>
	</thead>
  <% @topics.each do |topic| %>
      <tr>
        <th><span class="rounded"><b><%= topic.body %></b></span></th>
　      <td><span class="vote"><b><%= topic.polls.count %></b></span><span>票</span><br></td>
　    </tr>
  <% end %>
  </table>
<!--トップ投票数-->
  <div>
    <h3><b>TOP VOTE</b></h3>
    <% @top_topics.each do |topic| %>
      <th><span class="rounded"><b><%= topic.body %></b></span></th>
　    <td><span class="vote"><b><%= topic.polls.count %></b></span><span>票</span><br></td>
　  <% end %>
  </div>
</div>


<!--データ取得-->
<div id="topics">
  <% @topics.each do |topic| %>
    <div class="topic" data-topic="<%= topic.body %>"></div>
    <% topic.polls.count %>
  <% end %>
</div>
<div id="polls">
  <% @topics.each do |topic| %>
    <% topic.body %>
    <div class="poll" data-poll="<%= topic.polls.count %>"></div>
  <% end %>
</div>





<!--javascript-->
<svg width="500" height="50">
</svg>
<script>
  // 1. データの準備
  var e = document.getElementById('topics')
  var i = document.getElementById('polls')//constは最近のjavascriptの書き方
  var topics = []
  for (let number = 0; number < e.children.length; number++) {
  // topics = e.children[number].getAttribute('data-topic');
  var hash = { 'name': e.children[number].getAttribute('data-topic'), 'value': i.children[number].getAttribute('data-poll') }
  topics.push(hash)
  }
  console.log(topics)

  var dataset = topics
  var width = 400; // グラフの幅
  var height = 300; // グラフの高さ
  var radius = Math.min(width, height) / 2 - 10;

  // 2. SVG領域の設定
  var svg = d3.select("#poll_chart").append("svg").attr("width", width).attr("height", height);

  g = svg.append("g").attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

  // 3. カラーの設定
  var color = d3.scaleOrdinal()
    .range(["#DC3912", "#3366CC", "#109618", "#FF9900", "#990099"]);

  // 4. pieチャートデータセット用関数の設定
  var pie = d3.pie()
    .value(function(d) { return d.value; })
    .sort(null);

  // 5. pieチャートSVG要素の設定
  var pieGroup = g.selectAll(".pie")
    .data(pie(dataset))
    .enter()
    .append("g")
    .attr("class", "pie");

  arc = d3.arc()
    .outerRadius(radius)
    .innerRadius(0);

  pieGroup.append("path")
    .attr("d", arc)
    .attr("fill", function(d) { return color(d.index) })
    .attr("opacity", 0.75)
    .attr("stroke", "white");

  // 6. pieチャートテキストSVG要素の設定
  var text = d3.arc()
    .outerRadius(radius - 30)
    .innerRadius(radius - 30);

  pieGroup.append("text")
    .attr("fill", "black")
    .attr("transform", function(d) { return "translate(" + text.centroid(d) + ")"; })
    .attr("dy", "5px")
    .attr("font", "10px")
    .attr("text-anchor", "middle")
    .text(function(d) { return d.data.name; });
    </script>
</div>

app/views/users/show.html.erb
<h2>マイページ</h2>
<div class="col-xs-4">
<div><span class="rounded under-line"><b>ニックネーム</b></span><p class="margin-top-xs"><%= @user.name %></p></div><br>
<div><span class="rounded under-line"><b>メールアドレス</b></span><p class="margin-top-xs"><%= @user.email %></p></div><br>
<div><%= link_to "お題登録", new_vote_path, class:"btn btn-primary" %></div>
</div>

<div class="col-xs-8">
<table class="table">
  <thead>
		<tr>
			<th>タイトル</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= link_to vote.title, vote_path(vote), class:"rounded black"%></td>
        <td>
          <% if vote.status == true %>
            <p><%= link_to "投票を終了する", vote_path(vote), method: :patch, class: "btn btn-warning" %></p>
          <% elsif vote.status == false %>
            <p><%= link_to "投票結果へ", result_path(vote) %></p>
          <% end %>
        </td>
        <td><p><%= link_to "削除", vote_path(vote), method: :delete, class: "btn-sm btn-danger" %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/votes/complete.html.erb
<h2>お題登録完了</h2>

app/views/votes/index.html.erb
<h2>お題投票一覧</h2>
<table class="table">
  <thead>
    <tr>
			<th>タイトル</th>
			<th>本文</th>
		</tr>
	</thead>
  <tbody>
    <% @votes.each do |vote| %>
      <% if vote.status == true %>
        <tr>
          <td><%= link_to vote.title, vote_path(vote), class:"rounded black" %></td>
          <td><%= vote.body %></td>
        </tr>
      <% elsif vote.status == false %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/votes/new.html.erb
<h2>お題登録</h2>
<%= render "layouts/error", resource: @vote %>
<%= form_with model: @vote, local:true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body%>
  </div>
  <%= f.label :"お題" %>
  <%= f.fields_for :topics do |topic| %>
    <div class="margin-top-xs">
      <%= topic.text_field :body %>
    </div>
  <% end %>

  <div class="actions row margin-top-xs">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
  <% end %>

app/views/votes/show.html.erb
<h2>お題投票詳細</h2>
<div class="gothic">
  <span><b>お題　　</b></span><span class="font-md"><%= @vote.title %></span>
</div>
<div class="gothic">
  <span><b>本文　　</b></span><span class="font-md"><%= @vote.body %></span>
</div>

<!--each do-->
<div>
  <table class="table table-bordered">
    <thead>
		<tr>
			<th>お題</th>
			<th>票数</th>
		</tr>
	</thead>
  <% @topics.each do |topic| %>
      <tr>
        <th><span class="rounded"><b><%= topic.body %></b></span></th>
　      <td><span class="vote"><b><%= topic.polls.count %></b></span><span>票</span><br></td>
　    </tr>
  <% end %>
  </table>



<!--投票機能-->
  <div class="margin-top-md">
    <% if Poll.where(topic_id: @topics.ids).where(user_id: current_user.id).size > 0 %>
      <td>
        <span class="label label-warning font-md">投票済みです</span>
      </td>
    <% else %>
      <td>
        <div class="margin-bottom-md"><span class="label label-info font-md">投票してください</span></div>
          <%= form_with(model: @poll, url: vote_topic_polls_path(@vote,@topics), method: :post, local: true) do |f| %>
            <% @topics.each do |topic| %>
            <div>
              <%= f.radio_button(:topic_id, topic.id) %>
              <%= f.label(:topic_id, topic.body, value: topic.body)  %>
            </div>
            <% end %>
            <%= f.submit "投票する", class: 'btn btn-primary' %>
          <% end %>
        <!--<%#= link_to vote_topic_polls_path(@vote,topic), method: :post do %>-->
        <!--  <span class="btn radio-btn"></span>-->
        <!--<#% end %>-->
      </td>
    <% end %>
  </div>



</div>